# Generated by Django 4.0.3 on 2022-03-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_client_image_alter_project_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('linkin', models.URLField()),
                ('github', models.URLField()),
                ('instagram', models.URLField()),
            ],
        ),
    ]
